services:
  db:
    image: postgres:15
    container_name: simplifica
    environment:
      POSTGRES_USER: ypezoa
      POSTGRES_PASSWORD: hh9m3m34
      POSTGRES_DB: bm_simplifica
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: simplifica_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@simplifica.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build: .
    container_name: myapp
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ypezoa
      DB_PASSWORD: hh9m3m34
      DB_NAME: bm_simplifica
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp # para que air use cache sin interferir con el código

volumes:
  db_data:
  pgadmin_data:
